### ISSUE TITLE
Saving does not go back to the summary page

### ISSUE THREAD

**Issue by fscanu** [dturrina/votesmanager#10]
After vote for a competitor (clicking in the Save Votes button), the page does not go back to the competitors list. 
I think will be a good enhancemente, place another button or change the action of the save button.

**Comment by NezSpencer** [comment]
just fixed this now but I trying to see if I can fix issue #6 before I make a pull request

**Comment by dturrina** [comment]
Should you manage to solve both of them, I'd suggest a new release of the app. I'd eventually work on it during the weekend.
