### ISSUE TITLE
Code not compiling: cannot find symbol variable SUM

### ISSUE THREAD

**Issue by NezSpencer** [dturrina/votesmanager#13]
After I forked and cloned the project, I tried compiling on android studio but compilation failed with the error message: __Error:(225, 59) error: cannot find symbol variable SUM__. 

On checking, I discovered that __Aggregator.SUM__ used in __XmlManager.java__ is not declared in __Aggregator.java__ instead the closest to it is __Aggregator.SSUM__. 

When I changed all instances of __Aggregator.SUM__ to __Aggregator.SSUM__ it compiled successfully.

Did anyone experience notice this?

@dturrina Am I right to change __Aggregator.SUM__ to __Aggregator.SSUM__? if yes, should I make a pull request?

**Comment by dturrina** [comment]
Yes please it's OK to change Aggregator.SUM to Aggregator.SSUM, and please make a pull request.
Thank you so much, I did not notice it.

And, welcome to VotesManager!

**Comment by NezSpencer** [comment]
thanks :)

**Comment by NezSpencer** [comment]
Also, after building in android studio, my classpath in build.gradle changed as shown here:
![diff](https://cloud.githubusercontent.com/assets/11639214/12294243/030b797e-b9f9-11e5-9d67-94d49963080c.PNG)

should I also add and commit my build.gradle ?

**Comment by dturrina** [comment]
Sure! It will be useful for other users, so that they will download a "compile-ready" project.
And... well, sorry it wasn't... :)

**Comment by dturrina** [comment]
I believe it is fixed. Thank you @NezSpencer! I hope you'll enjoy working - or just surfing - on VotesManager!
