### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by kltention** [dturrina/votesmanager#18]
Hi, I am interested in working on your repo. However, I wanted to contact you via email. Is this possible?

**Comment by dturrina** [comment]
Look for VotesManager on OpenHatch and contact me through it. Thanks.
https://openhatch.org/projects/VotesManager

**Comment by kltention** [comment]
I'm just seeing this. Sorry it took me so long. I'm not use to GITHUB l

**Comment by dturrina** [comment]
Did you manage to find out how to write me? I saw no message so far

**Comment by kltention** [comment]
No I did not. What IDE are you using to develop? If possible can you email me @ Kltention@gmail.com
